services:
  
  haproxy_db:
    image: haproxy:2.9
    ports:
      - "3000:3000"
    volumes:
      - ./haproxy_db.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    networks: [cluster]


  patroni:
    build: ./patroni        
    environment:
      PATRONI_ETCD3_HOSTS: etcd1:2379,etcd2:2379,etcd3:2379
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bank
    volumes:
      - patroni_data:/var/lib/postgresql/data
    networks: [cluster]
    depends_on:
      - etcd1
      - etcd2
      - etcd3
    deploy:
      replicas: 1   
    ports:
      - "8008:8008"

  etcd1:
    image: quay.io/coreos/etcd:v3.5.13
    command: >
      /usr/local/bin/etcd
      --name etcd1
      --data-dir /etcd-data
      --initial-advertise-peer-urls http://etcd1:2380
      --listen-peer-urls http://0.0.0.0:2380
      --listen-client-urls http://0.0.0.0:2379
      --advertise-client-urls http://etcd1:2379
      --initial-cluster etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      --initial-cluster-state new
      --initial-cluster-token patroni
    networks:
      - cluster

  etcd2:
    image: quay.io/coreos/etcd:v3.5.13
    command: >
      /usr/local/bin/etcd
      --name etcd2
      --data-dir /etcd-data
      --initial-advertise-peer-urls http://etcd2:2380
      --listen-peer-urls http://0.0.0.0:2380
      --listen-client-urls http://0.0.0.0:2379
      --advertise-client-urls http://etcd2:2379
      --initial-cluster etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      --initial-cluster-state new
      --initial-cluster-token patroni
    networks:
      - cluster

  etcd3:
    image: quay.io/coreos/etcd:v3.5.13
    command: >
      /usr/local/bin/etcd
      --name etcd3
      --data-dir /etcd-data
      --initial-advertise-peer-urls http://etcd3:2380
      --listen-peer-urls http://0.0.0.0:2380
      --listen-client-urls http://0.0.0.0:2379
      --advertise-client-urls http://etcd3:2379
      --initial-cluster etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      --initial-cluster-state new
      --initial-cluster-token patroni
    networks:
      - cluster


  api:
    image: node:20-alpine
    deploy:
      replicas: 3
    working_dir: /app
    volumes:
      - ./api:/app
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: bank
      DB_PORT: 5432
      NODE_ENV: development
    command: sh -c "npm install && npm start"

  haproxy_api:
    image: haproxy:2.9
    container_name: haproxy
    ports:
      - "3001:3000"
    depends_on:
      - api
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy_api.cfg:ro

networks:
  cluster:

volumes:
  pgdata:
  patroni_data:

