services:
  db:
    image: postgres:15
    container_name: banco_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bank
    ports:
      - "5432:5432" # 🔹 permite acesso via DBeaver (localhost:5432)
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d bank"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./api:/app # 🔹 monta seu código local dentro do container
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: bank
      DB_PORT: 5432
      NODE_ENV: development
    ports:
      - "3000:3000" # 🔹 acessível em http://localhost:3000
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "npm install && npm start"

volumes:
  pgdata:

