CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar UNIQUE NOT NULL,
  "password" varchar NOT NULL,
  "balance" numeric(18,2) DEFAULT 0,
  "created_at" timestamp DEFAULT (now()),
  "deleted" boolean NOT NULL DEFAULT false
);

CREATE TABLE "operations" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "operation_type" varchar NOT NULL,
  "amount" numeric(18,2) NOT NULL,
  "balance_before" numeric(18,2) NOT NULL,
  "related_user" integer,
  "created_at" timestamp DEFAULT (now())
);

COMMENT ON COLUMN "users"."balance" IS 'Saldo atual do usuário';

COMMENT ON COLUMN "operations"."operation_type" IS 'deposit | withdraw | transfer_send | transfer_recv';

COMMENT ON COLUMN "operations"."amount" IS 'Valor da operação';

COMMENT ON COLUMN "operations"."balance_before" IS 'Saldo antes da operação';

COMMENT ON COLUMN "operations"."related_user" IS 'Usuário envolvido em uma transferência';

ALTER TABLE "operations" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "operations" ADD FOREIGN KEY ("related_user") REFERENCES "users" ("id");

-- ==============================
-- GERAÇÃO DE DADOS DE TESTE
-- ==============================

-- Parâmetros gerais
DO $$
DECLARE
    v_user_count INT;
    v_ops_per_user INT;
    v_total_ops INT := 50000;
    v_uid INT;
    v_related INT;
    v_optype TEXT;
    v_amt NUMERIC(18,2);
    v_bal NUMERIC(18,2);
BEGIN
    RAISE NOTICE '=== Gerando usuários ===';

    -- Define aleatoriamente entre 100 e 200 usuários
    v_user_count := 100 + floor(random() * 100)::INT;

    -- Cria usuários
    INSERT INTO users (username, password, balance)
    SELECT
        'user_' || i,
        md5(random()::text),
        (random() * 1000)::NUMERIC(18,2)
    FROM generate_series(1, v_user_count) s(i);

    -- Calcula quantas operações por usuário (aprox)
    v_ops_per_user := CEIL(v_total_ops::NUMERIC / v_user_count);

    RAISE NOTICE '=== Gerando ~% operações para % usuários ===', v_total_ops, v_user_count;

    FOR v_uid IN SELECT id FROM users LOOP
        FOR i IN 1..v_ops_per_user LOOP
            v_amt := round((random() * 200)::numeric + 1, 2);  -- valor entre 1 e 200
            v_bal := (SELECT balance FROM users WHERE id = v_uid);

            -- Sorteia tipo da operação
            v_optype := CASE
                WHEN random() < 0.4 THEN 'deposit'
                WHEN random() < 0.8 THEN 'withdraw'
                WHEN random() < 0.9 THEN 'transfer_send'
                ELSE 'transfer_recv'
            END;

            IF v_optype = 'deposit' THEN
                INSERT INTO operations (user_id, operation_type, amount, balance_before, created_at)
                VALUES (v_uid, 'deposit', v_amt, v_bal, now() - (random() * interval '90 days'));
                UPDATE users SET balance = balance + v_amt WHERE id = v_uid;

            ELSIF v_optype = 'withdraw' THEN
                INSERT INTO operations (user_id, operation_type, amount, balance_before, created_at)
                VALUES (v_uid, 'withdraw', v_amt, v_bal, now() - (random() * interval '90 days'));
                UPDATE users SET balance = GREATEST(balance - v_amt, 0) WHERE id = v_uid;

            ELSIF v_optype = 'transfer_send' THEN
                v_related := (SELECT id FROM users WHERE id <> v_uid ORDER BY random() LIMIT 1);
                INSERT INTO operations (user_id, operation_type, amount, balance_before, related_user, created_at)
                VALUES (v_uid, 'transfer_send', v_amt, v_bal, v_related, now() - (random() * interval '90 days'));
                UPDATE users SET balance = GREATEST(balance - v_amt, 0) WHERE id = v_uid;

                -- Cria operação correspondente de recebimento
                INSERT INTO operations (user_id, operation_type, amount, balance_before, related_user, created_at)
                VALUES (v_related, 'transfer_recv',
                        v_amt,
                        (SELECT balance FROM users WHERE id = v_related),
                        v_uid,
                        now() - (random() * interval '90 days'));
                UPDATE users SET balance = balance + v_amt WHERE id = v_related;
            END IF;
        END LOOP;
    END LOOP;

    RAISE NOTICE '=== População finalizada ===';
END$$;

-- ==============================
-- ÍNDICES RECOMENDADOS
-- ==============================
CREATE INDEX IF NOT EXISTS idx_operations_user_id ON operations(user_id);
CREATE INDEX IF NOT EXISTS idx_operations_related_user ON operations(related_user);
CREATE INDEX IF NOT EXISTS idx_operations_type ON operations(operation_type);
CREATE INDEX IF NOT EXISTS idx_operations_created_at ON operations(created_at);



